/*
 * Ultima IV - Quest Of The Avatar
 * (c) Copyright 1987 Lord British
 * reverse-coded by Ergonomy Joe in 2012
 */

#ifndef __U4_LOC_H__
#define __U4_LOC_H__


#define LOC_BUILDINGS    0x01

/*====---- ----====*/
#define LOC_CASTLES      0x01

#define LOC_LCB          0x01
#define LOC_LYCAEUM      0x02
#define LOC_EMPATH       0x03
#define LOC_SERPENT      0x04

/*====---- ----====*/
#define LOC_TOWNS        0x05

#define LOC_MOONGLOW     0x05
#define LOC_BRITAIN      0x06
#define LOC_JHELOM       0x07
#define LOC_YEW          0x08
#define LOC_MINOC        0x09
#define LOC_TRINSIC      0x0a
#define LOC_SKARA        0x0b
#define LOC_MAGINCIA     0x0c

#define LOC_PAWS         0x0d
#define LOC_DEN          0x0e
#define LOC_VESPER       0x0f
#define LOC_COVE         0x10

/*====---- ----====*/
#define LOC_DUNGEONS     0x11

#define LOC_DECEIT       0x11
#define LOC_DESPISE      0x12
#define LOC_DESTARD      0x13
#define LOC_WRONG        0x14
#define LOC_COVETOUS     0x15
#define LOC_SHAME        0x16
#define LOC_HYTHLOTH     0x17
#define LOC_ABYSS        0x18

/*====---- ----====*/
#define LOC_SHRINES      0x19

#define LOC_HONESTY      0x19
#define LOC_COMPASSION   0x1a
#define LOC_VALOR        0x1b
#define LOC_JUSTICE      0x1c
#define LOC_SACRIFICE    0x1d
#define LOC_HONOR        0x1e
#define LOC_SPIRITUALITY 0x1f
#define LOC_HUMILITY     0x20

#endif
