/*
 * Ultima IV - Quest Of The Avatar
 * (c) Copyright 1987 Lord British
 * reverse-coded by Ergonomy Joe in 2012
 */

#ifndef __U4_SCAN_H__
#define __U4_SCAN_H__

#define KBD_ESC    0x011b
#define KBD_BS     0x0e08
#define KBD_0e7f   0x0e7f
#define KBD_SPACE  0x3920
#define KBD_ENTER  0x1c0d

#define KBD_HOME   0x4700
#define KBD_UP     0x4800
#define KBD_UP_    0x487e
#define KBD_PGUP   0x4900
#define KBD_LEFT   0x4B00
#define KBD_LEFT_  0x4b7c
#define KBD_RIGHT  0x4D00
#define KBD_RIGHT_ 0xf400
#define KBD_END    0x4f00
#define KBD_DOWN   0x5000
#define KBD_DOWN_  0x5060
#define KBD_PGDN   0x5100

#define KBD_1 0x0231
#define KBD_2 0x0332
#define KBD_3 0x0433
#define KBD_4 0x0534
#define KBD_5 0x0635
#define KBD_6 0x0736
#define KBD_7 0x0837
#define KBD_8 0x0938
#define KBD_0 0x0b30

#define KBD_A 0x1E61
#define KBD_B 0x3062
#define KBD_C 0x2E63
#define KBD_D 0x2064
#define KBD_E 0x1265
#define KBD_F 0x2166
#define KBD_G 0x2267
#define KBD_H 0x2368
#define KBD_I 0x1769
#define KBD_J 0x246A
#define KBD_K 0x256B
#define KBD_L 0x266C
#define KBD_M 0x326D
#define KBD_N 0x316E
#define KBD_O 0x186F
#define KBD_P 0x1970
#define KBD_Q 0x1071
#define KBD_R 0x1372
#define KBD_S 0x1F73
#define KBD_T 0x1474
#define KBD_U 0x1675
#define KBD_V 0x2F76
#define KBD_W 0x1177
#define KBD_X 0x2D78
#define KBD_Y 0x1579
#define KBD_Z 0x2c7a

#define KBD_CTRL_S 0x1f13
#define KBD_ALT_Z  0x2c00

#endif
